// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmeapMQZT-viahdvQTtjJCDEDQBXN5OcY',
    appId: '1:946397682513:web:808e387ff6cb27c4679170',
    messagingSenderId: '946397682513',
    projectId: 'todo-list-a6c6b',
    authDomain: 'todo-list-a6c6b.firebaseapp.com',
    storageBucket: 'todo-list-a6c6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_-BqDsyKMTAMq-XMVyMyTXVGLFOl2D6s',
    appId: '1:946397682513:android:c040198e7d36dd39679170',
    messagingSenderId: '946397682513',
    projectId: 'todo-list-a6c6b',
    storageBucket: 'todo-list-a6c6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfqF4gWyKEcVqncSLjFF2Nj6t9LrgQjc',
    appId: '1:946397682513:ios:da3ed3ed241b7caa679170',
    messagingSenderId: '946397682513',
    projectId: 'todo-list-a6c6b',
    storageBucket: 'todo-list-a6c6b.appspot.com',
    iosClientId: '946397682513-6c0om2ckuem3vrdl7ggfc57fndejc2v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmfqF4gWyKEcVqncSLjFF2Nj6t9LrgQjc',
    appId: '1:946397682513:ios:da3ed3ed241b7caa679170',
    messagingSenderId: '946397682513',
    projectId: 'todo-list-a6c6b',
    storageBucket: 'todo-list-a6c6b.appspot.com',
    iosClientId: '946397682513-6c0om2ckuem3vrdl7ggfc57fndejc2v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmeapMQZT-viahdvQTtjJCDEDQBXN5OcY',
    appId: '1:946397682513:web:1d8ffc4b48feb8ed679170',
    messagingSenderId: '946397682513',
    projectId: 'todo-list-a6c6b',
    authDomain: 'todo-list-a6c6b.firebaseapp.com',
    storageBucket: 'todo-list-a6c6b.appspot.com',
  );
}
